<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInita80cbf703733baba97b1dc35a089dd30
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('StellarWP\Learndash\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \StellarWP\Learndash\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInita80cbf703733baba97b1dc35a089dd30', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \StellarWP\Learndash\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInita80cbf703733baba97b1dc35a089dd30', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\StellarWP\Learndash\Composer\Autoload\ComposerStaticInita80cbf703733baba97b1dc35a089dd30::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        $filesToLoad = \StellarWP\Learndash\Composer\Autoload\ComposerStaticInita80cbf703733baba97b1dc35a089dd30::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }

        return $loader;
    }
}
