<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitf8d0124abdb38ad95a01cda7bfd14b87
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('LearnDash\Instructor_Role\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \LearnDash\Instructor_Role\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInitf8d0124abdb38ad95a01cda7bfd14b87', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \LearnDash\Instructor_Role\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitf8d0124abdb38ad95a01cda7bfd14b87', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\LearnDash\Instructor_Role\Composer\Autoload\ComposerStaticInitf8d0124abdb38ad95a01cda7bfd14b87::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
